// ...existing code...

const Post = ({ post }: Props) => {
  // ...existing code...
  return (
    <div>
      // ...existing code...
      {/* 删除评论区组件 */}
      // ...existing code...
    </div>
  )
}
// ...existing code...
